--谢滨旭
--审查录入比对信息表
DROP TABLE OPAS_REVIEENTRY_COMPARE_INFO;
CREATE TABLE OPAS_REVIEENTRY_COMPARE_INFO ( 
	APP_ID char(16) NOT NULL primary key,
	APPLY_INPUTFULL	char(1) NULL,
	SIGN_FULL char(1) NULL,
	NATIONAL_INUTFULL   char(1) NULL,
	CERTIFI_PERIODFULL char(1) NULL,
	APPLY_WORK_TURE char(1) NULL,
	PEOBANK_COMPANY_NAME_ADDR char(1) NULL,
	PEOBANK_COMPANY_NAME_TEL char(1) NULL,
	COMPANY_114_NAME_ADDR char(1) NULL,
	COMPANY_114_NAME_TEL char(1) NULL,
	PYUAN_COMPANY_NAME_ADDR char(1) NULL,
	PYUAN_COMPANY_NAME_TEL char(1) NULL,
	NO_OFFICWEB_NAME_ADDR char(1) NULL,
	NO_OFFICWEB_NAME_TEL char(1) NULL,
	OTHER_THIRD_NAME_ADDR char(1) NULL,
	OFFICWEB_NAME_ADDR char(1) NULL,
	OFFICWEB_NAME_TEL char(1) NULL,
	THIRDDATA_ADDR char(1) NULL,
	APPLY_WORKINFO_TURE char(1) NULL,
	SBANDGJJ_6MONTHS_STATUS char(1) NULL,
	BUSINETWORK_LEGAL char(1) NULL,
	OTHERS char(1) NULL,
	OTHER_MEMO char(1) NULL,
	PUB_POLICE char(1) NULL,
	BUSINETWORK_MINOR char(1) NULL,
	PEOBANK_FIRSTCARD_6MONTHS char(1) NULL,
	INSURANCE char(1) NULL,
	APPLYER_TRUE char(1) NULL,
	PEOBANK_PHONE char(1) NULL,
	THIRD_PHONE char(1) NULL,
	OTHERTHIRD_INFO char(1) NULL
	);
	COMMENT ON TABLE OPAS_REVIEENTRY_COMPARE_INFO IS '审查录入比对信息表';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.APP_ID IS '条形码';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.APPLY_INPUTFULL IS '抄录文字完整有效';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.SIGN_FULL IS '签名完整有效';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.NATIONAL_INUTFULL IS '国籍填写有效';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.APPLY_WORK_TURE IS '申请单位真实';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.CERTIFI_PERIODFULL IS '身份证有效期填写完整有效';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PEOBANK_COMPANY_NAME_ADDR IS '人行单名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PEOBANK_COMPANY_NAME_TEL IS '人行单名+单电';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.COMPANY_114_NAME_ADDR IS '114单名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.COMPANY_114_NAME_TEL IS '114单名+单电';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PYUAN_COMPANY_NAME_ADDR IS '鹏元名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PYUAN_COMPANY_NAME_TEL IS '鹏元单名+单电';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.NO_OFFICWEB_NAME_ADDR IS '非官网单名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.NO_OFFICWEB_NAME_TEL IS '非官网单名+单电';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OTHER_THIRD_NAME_ADDR IS '其他第三方信息单名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OFFICWEB_NAME_ADDR IS '官网单名+单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OFFICWEB_NAME_TEL IS '官网单名+单电';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.THIRDDATA_ADDR IS '第三方数据单址';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.APPLY_WORKINFO_TURE IS '申请人工作信息真实';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.SBANDGJJ_6MONTHS_STATUS IS '社保或公积金信息近6个月缴交状态正常';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.BUSINETWORK_LEGAL IS '工商网法人';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OTHERS IS '其他';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OTHER_MEMO IS '其他注明';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PUB_POLICE IS '增强公安';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.BUSINETWORK_MINOR IS '工商网股东';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PEOBANK_FIRSTCARD_6MONTHS IS '人行首张贷记卡发卡日期大于6个月';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.INSURANCE IS '保监会';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.APPLYER_TRUE IS '申请人真实';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.PEOBANK_PHONE IS '人行手机';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.THIRD_PHONE IS '第三方数据手机';
	COMMENT ON COLUMN OPAS_REVIEENTRY_COMPARE_INFO.OTHERTHIRD_INFO IS '其他第三方信息';
	
	